from flask import Flask, request, jsonify
from flask_cors import CORS
from ultralytics import YOLO
import base64
import io
import os
from PIL import Image
import google.generativeai as genai
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY and GEMINI_API_KEY != "PASTE_YOUR_API_KEY_HERE":
    genai.configure(api_key=GEMINI_API_KEY)
    # Using the Gemini 2.5 Flash multimodal model (Free Tier Compatible)
    gemini_model = genai.GenerativeModel('gemini-2.0-flash')
else:
    gemini_model = None
    print("⚠️ Warning: Gemini API Key not found in .env! Medical Reports will be disabled.")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if OPENAI_API_KEY:
    openai_client = OpenAI(api_key=OPENAI_API_KEY)
else:
    openai_client = None
    print("⚠️ Warning: OpenAI API Key not found in .env!")

GROK_API_KEY = os.getenv("GROK_API_KEY")
if GROK_API_KEY:
    grok_client = OpenAI(
        api_key=GROK_API_KEY,
        base_url="https://api.x.ai/v1"
    )
else:
    grok_client = None
    print("⚠️ Warning: Grok API Key not found in .env!")

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if GROQ_API_KEY:
    groq_client = OpenAI(
        api_key=GROQ_API_KEY,
        base_url="https://api.groq.com/openai/v1"
    )
else:
    groq_client = None
    print("⚠️ Warning: Groq API Key not found in .env!")

app = Flask(__name__)
CORS(app) # Allow React to talk to this server

def generate_fallback_report(predictions, role):
    """Generate a structured report from YOLO detections when Gemini is unavailable."""
    if not predictions:
        if role == 'patient':
            return "**Good news!** Our AI scan did not detect any major concerns in your dental image. Keep up your great oral hygiene routine!\n\n**Preventive Plan**\n- Brush twice daily with fluoride toothpaste\n- Floss every evening\n- Visit your dentist every 6 months for a routine checkup"
        else:
            return "**Clinical Summary**\nNo significant pathological findings detected by the AI diagnostic system in this image.\n\n**Preventive Plan**\n- Continue routine monitoring\n- Schedule standard 6-month recall\n- Reinforce home care instructions with patient"

    # Count and categorize findings
    counts = {}
    for p in predictions:
        label = p['class']
        counts[label] = counts.get(label, 0) + 1

    findings_text = ', '.join([f"{v}x {k}" for k, v in counts.items()])
    avg_conf = sum(p['confidence'] for p in predictions) / len(predictions)

    if role == 'patient':
        report = f"**Your Dental Scan Summary**\n\nOur AI system has completed your scan and identified some areas to keep an eye on: **{findings_text}**.\n\nDon't worry — early detection means easier treatment! Your dentist will guide you on the best next steps.\n\n**Preventive Plan**\n- Schedule an appointment with your dentist soon to discuss these findings\n- Brush gently twice a day and use fluoride toothpaste\n- Avoid sugary foods and drinks between meals\n- Floss daily to prevent gum issues\n\n*This report was generated by the AI detection system (confidence: {avg_conf*100:.0f}%).*"
    else:
        lines = ["**Clinical AI Analysis Report**\n"]
        lines.append(f"**Detected Findings:** {findings_text}")
        lines.append(f"**Average Detection Confidence:** {avg_conf*100:.1f}%\n")
        lines.append("**Findings Breakdown:**")
        for label, count in counts.items():
            relevant = [p for p in predictions if p['class'] == label]
            avg = sum(p['confidence'] for p in relevant) / len(relevant)
            lines.append(f"- **{label}**: {count} instance(s) detected (avg. confidence: {avg*100:.0f}%)")
        lines.append("\n**Preventive Plan**")
        if any('caries' in k.lower() or 'cavity' in k.lower() for k in counts):
            lines.append("- Caries detected: Consider excavation and restoration. Evaluate for pulp involvement.")
        if any('gum' in k.lower() or 'swelling' in k.lower() for k in counts):
            lines.append("- Gingival inflammation noted: Recommend scaling, root planing, and home care reinforcement.")
        if any('missing' in k.lower() for k in counts):
            lines.append("- Missing tooth: Discuss prosthetic options — implant, bridge, or partial denture.")
        if any('discolor' in k.lower() for k in counts):
            lines.append("- Discoloration present: Assess for intrinsic vs extrinsic cause. Consider bleaching or veneer.")
        lines.append("- Schedule follow-up in 4–6 weeks to monitor treatment response.")
        lines.append(f"\n*Note: Full AI narrative report unavailable — API quota limit reached. Detection results are from the YOLOv8 model at {avg_conf*100:.0f}% average confidence.*")
        report = '\n'.join(lines)

    return report


# Load ALL 5 models!
MODEL_PATHS = ['best (1).pt', 'best (2).pt', 'best (3).pt', 'best (4).pt', 'best (5).pt']
models = []
for path in MODEL_PATHS:
    try:
        model = YOLO(path)
        models.append(model)
        print(f"✅ Successfully loaded {path}")
    except Exception as e:
        print(f"⚠️ Warning: Could not load {path}. Make sure it is inside the ml-engine folder! Error: {e}")

@app.route('/analyze', methods=['POST'])
def analyze_image():
    if not models:
        return jsonify({"error": "No models loaded on the server. Please check the terminal!"}), 500

    try:
        # Get JSON from React
        data_payload = request.get_json(force=True)
        base64_data = data_payload.get("image", "")
        role = data_payload.get("role", "doctor")
        
        # Decode the image
        image_data = base64.b64decode(base64_data)
        image = Image.open(io.BytesIO(image_data)).convert('RGB')
        
        width, height = image.size
        
        # Format results exactly how the React app expects them
        predictions = []
        
        # Run YOLO inference for EVERY model and combine the results!
        for model in models:
            results = model(image)
            for r in results:
                boxes = r.boxes
                for box in boxes:
                    # get box coordinates in center x, center y, width, height format
                    xywh = box.xywh[0].tolist() 
                    conf = float(box.conf[0])
                    cls = int(box.cls[0])
                    class_name = model.names[cls]
                    
                    predictions.append({
                        "class": class_name,
                        "confidence": conf,
                        "x": xywh[0],
                        "y": xywh[1],
                        "width": xywh[2],
                        "height": xywh[3]
                    })
                    
        # --- PRIMARY ANALYSIS (OpenAI / Gemini) ---
        gemini_report = None
        
        # Formulate prompts
        if role == 'patient':
            prompt = f"""
            You are a friendly, reassuring, and highly skilled dentist speaking directly to a patient.
            Please analyze the attached dental photograph. 
            (Note: Our internal system flagged these areas: {predictions}, but use your judgment.)
            
            Provide a VERY simple, brief, and easy-to-understand summary of what you see.
            Use plain English. DO NOT use scary medical jargon or complex formatting.
            Provide a few simple, reassuring next steps for the patient to take under the explicit heading "**Preventive Plan**". Do not use the words "Treatment Plan".
            Keep the entire response short and concise.
            """
        else:
            prompt = f"""
            You are a world-class Chief Dental Officer. 
            Please analyze the attached clinical dental photograph. 
            (Note: Our internal diagnostic system flagged the following potential areas of interest: {predictions}, but you should make your own independent clinical assessment.)
            
            Provide a highly professional, comprehensive clinical summary of what you see in the image. 
            Then, you MUST provide the next steps under the explicit heading "**Preventive Plan**". Do not use the words "Treatment Plan" or "Recommended Treatment Plan" anywhere.
            Format your response clearly. Speak directly to the attending dentist. Be confident and precise.
            CRITICAL INSTRUCTION: You MUST end your response immediately after the preventive plan. DO NOT include ANY sign-offs, signatures, or closing remarks whatsoever (e.g. absolutely no "Sincerely," or "Chief Dental Officer").
            """

        # Try Groq First if available
        if groq_client:
            try:
                print(f"🧠 Asking Groq (llama-3.2-11b-vision-preview) to analyze the image for a {role}...")
                response = groq_client.chat.completions.create(
                    model="llama-3.2-11b-vision-preview",
                    messages=[
                        {
                            "role": "user",
                            "content": [
                                {"type": "text", "text": prompt},
                                {
                                    "type": "image_url",
                                    "image_url": {
                                        "url": f"data:image/jpeg;base64,{base64_data}"
                                    }
                                }
                            ]
                        }
                    ]
                )
                gemini_report = response.choices[0].message.content.strip()
                print("✅ Groq report generated!")
            except Exception as e:
                print(f"❌ Groq Analysis Error: {e}")

        # Try Grok if Groq is not set up or failed
        if not gemini_report and grok_client:
            try:
                print(f"🧠 Asking Grok (grok-2-vision-beta) to analyze the image for a {role}...")
                response = grok_client.chat.completions.create(
                    model="grok-2-vision-beta",
                    messages=[
                        {
                            "role": "user",
                            "content": [
                                {"type": "text", "text": prompt},
                                {
                                    "type": "image_url",
                                    "image_url": {
                                        "url": f"data:image/jpeg;base64,{base64_data}"
                                    }
                                }
                            ]
                        }
                    ]
                )
                gemini_report = response.choices[0].message.content.strip()
                print("✅ Grok report generated!")
            except Exception as e:
                print(f"❌ Grok Analysis Error: {e}")

        # Try OpenAI if Grok is not set up or failed
        if not gemini_report and openai_client:
            try:
                print(f"🧠 Asking OpenAI (gpt-4o-mini) to analyze the image for a {role}...")
                response = openai_client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[
                        {
                            "role": "user",
                            "content": [
                                {"type": "text", "text": prompt},
                                {
                                    "type": "image_url",
                                    "image_url": {
                                        "url": f"data:image/jpeg;base64,{base64_data}"
                                    }
                                }
                            ]
                        }
                    ]
                )
                gemini_report = response.choices[0].message.content.strip()
                print("✅ OpenAI report generated!")
            except Exception as e:
                print(f"❌ OpenAI Analysis Error: {e}")
                
        # Try Gemini if OpenAI is not set up or failed
        if not gemini_report and gemini_model:
            try:
                print(f"🧠 Asking Gemini to analyze the image for a {role}...")
                response = gemini_model.generate_content([prompt, image])
                gemini_report = response.text
                print("✅ Gemini report generated!")
            except Exception as e:
                print(f"❌ Gemini Analysis Error: {e}")

        # Post-process report string formatting
        if gemini_report:
            # Forcefully remove any signatures the AI might have accidentally added
            if "Sincerely," in gemini_report:
                gemini_report = gemini_report.split("Sincerely,")[0].strip()
            if "Chief Dental Officer" in gemini_report:
                gemini_report = gemini_report.replace("Chief Dental Officer", "").strip()
        else:
            # Generate a smart fallback report from YOLO detections if both models failed
            print("⚠️ Using YOLO local detections fallback report.")
            gemini_report = generate_fallback_report(predictions, role)


        return jsonify({
            "image": {"width": width, "height": height},
            "predictions": predictions,
            "gemini_report": gemini_report
        })

    except Exception as e:
        print("Error during inference:", e)
        return jsonify({"error": str(e)}), 500

def generate_fallback_chat_reply(user_message, role):
    """Generate a high-quality local chatbot reply if both APIs are down/exhausted."""
    msg = user_message.lower()
    if role == "doctor":
        if "carie" in msg or "decay" in msg or "cavity" in msg:
            return "**SmileGuard AI (Clinical Guidance)**\n\nFor caries management, current evidence supports minimally invasive dentistry. Consider remineralization protocols (fluoride varnish, SDF) for non-cavitated lesions, and conservative restoration for cavitated dentinal lesions. Assess dietary risks, xerostomia factors, and patient compliance."
        elif "periodon" in msg or "gum" in msg or "bleed" in msg:
            return "**SmileGuard AI (Periodontal Guidance)**\n\nGingivitis and periodontitis management requires scaling and root planing (SRP). Evaluate periodontal pocket depths, bleeding on probing (BOP), and plaque index. Support with localized antimicrobials or chlorhexidine rinses if acute inflammation exists."
        elif "pain" in msg or "sensitiv" in msg:
            return "**SmileGuard AI (Pulpal/Periapical Guidance)**\n\nEtiology of dental pain must be isolated: check response to thermal stimuli (reversible vs. irreversible pulpitis) and percussion/palpation (apical periodontitis). Verify crack patterns via transillumination or bite tests."
        elif "brace" in msg or "ortho" in msg:
            return "**SmileGuard AI (Orthodontic Guidance)**\n\nEvaluate crowding, spacing, overbite/underbite, and skeletal relationship. Initial stages involve level and align, progressing to space closure, and final detailing. Emphasize oral hygiene during bracket treatment."
        else:
            return "**SmileGuard AI (Clinical Support)**\n\nNote: OpenAI and Gemini API endpoints are currently experiencing quota limits. General clinical reminder: diagnostic accuracy relies on combined clinical exam, radiographic findings, and patient history. Ensure patient follows custom preventive regimens."
    else:
        if "brush" in msg or "floss" in msg or "clean" in msg:
            return "Proper cleaning is key to great dental health! 🪥\n- **Brush**: Twice a day for 2 minutes using fluoride toothpaste and a soft-bristled brush.\n- **Floss**: Once every day to clean between teeth where brushes can't reach.\n- **Rinse**: Using an alcohol-free mouthwash helps fight plaque."
        elif "bleed" in msg or "gum" in msg:
            return "Bleeding gums are typically a sign of plaque buildup causing inflammation (gingivitis). Don't stop brushing! Continue gentle brushing, floss daily, and schedule a professional cleaning with your dentist to remove hardened tartar."
        elif "cavity" in msg or "decay" in msg or "hole" in msg:
            return "A cavity is a small hole formed by plaque bacteria eating away at your enamel. Once a cavity forms in the dentin, it cannot heal on its own and requires a dental filling. See your dentist soon so it doesn't grow and affect the nerve!"
        elif "pain" in msg or "ache" in msg or "hurt" in msg:
            return "Toothaches can be caused by deep cavities, gum infection, or a cracked tooth. Rinsing with warm salt water and taking over-the-counter pain relievers can help temporarily. Please visit a dentist as soon as possible for an X-ray and proper treatment."
        elif "brace" in msg or "ortho" in msg:
            return "With braces, keeping teeth clean is very important! Clean around brackets daily using interdental brushes, floss with a threader, and avoid sticky or hard foods that can break brackets. Visited your orthodontist regularly for adjustments."
        else:
            return "Hi there! Both our OpenAI and Gemini servers are currently experiencing high traffic (quota limits). Here are our gold-standard tips for a healthy smile:\n- Brush twice a day and floss daily\n- Limit sugary snacks and sodas\n- Drink water after meals\n- See your dentist every 6 months for a clean and exam!"

@app.route('/chat', methods=['POST'])
def chat():
    """AI Dental Chatbot endpoint."""
    try:
        data = request.get_json(force=True)
        user_message = data.get("message", "").strip()
        role = data.get("role", "patient")
        history = data.get("history", [])  # list of {sender, text}

        if not user_message:
            return jsonify({"reply": "Please type a message."}), 200

        # Build system prompt based on role
        if role == "doctor":
            system_prompt = """You are SmileGuard AI, an expert dental AI assistant for licensed dental professionals.
You assist dentists with clinical decision-making, treatment planning, diagnostic interpretation, and patient management.
Be precise, professional, and evidence-based. Use correct clinical terminology.
You can discuss: caries management, periodontal disease, restorations, orthodontics, oral surgery, radiology, dental materials, and infection control.
IMPORTANT: Always remind that final clinical judgment rests with the licensed dentist."""
        else:
            system_prompt = """You are SmileGuard AI, a friendly and caring dental health assistant for patients.
Help patients understand their dental health in simple, non-scary language.
You can answer questions about: oral hygiene, common dental procedures, pain management, diet and teeth, braces, whitening, and what to expect at dental visits.
Always be reassuring and encouraging. Remind patients to consult their dentist for personal medical advice.
NEVER diagnose conditions or recommend specific medications. Keep answers short, warm, and easy to understand."""

        reply = None

        # 1. Try Groq
        if groq_client:
            try:
                print(f"💬 Asking Groq to chat ({role})...")
                messages = [{"role": "system", "content": system_prompt}]
                for msg in history[-10:]:
                    role_name = "user" if msg["sender"] == "user" else "assistant"
                    messages.append({"role": role_name, "content": msg["text"]})
                messages.append({"role": "user", "content": user_message})

                completion = groq_client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=messages
                )
                reply = completion.choices[0].message.content.strip()
                print("✅ Groq chat reply generated!")
            except Exception as groq_err:
                print(f"❌ Groq Chat Error: {groq_err}")

        # 2. Try Grok fallback
        if not reply and grok_client:
            try:
                print(f"💬 Asking Grok to chat ({role})...")
                messages = [{"role": "system", "content": system_prompt}]
                for msg in history[-10:]:
                    role_name = "user" if msg["sender"] == "user" else "assistant"
                    messages.append({"role": role_name, "content": msg["text"]})
                messages.append({"role": "user", "content": user_message})

                completion = grok_client.chat.completions.create(
                    model="grok-beta",
                    messages=messages
                )
                reply = completion.choices[0].message.content.strip()
                print("✅ Grok chat reply generated!")
            except Exception as grok_err:
                print(f"❌ Grok Chat Error: {grok_err}")

        # 2. Try OpenAI fallback
        if not reply and openai_client:
            try:
                print(f"💬 Asking OpenAI to chat ({role})...")
                messages = [{"role": "system", "content": system_prompt}]
                for msg in history[-10:]:
                    role_name = "user" if msg["sender"] == "user" else "assistant"
                    messages.append({"role": role_name, "content": msg["text"]})
                messages.append({"role": "user", "content": user_message})

                completion = openai_client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=messages
                )
                reply = completion.choices[0].message.content.strip()
                print("✅ OpenAI chat reply generated!")
            except Exception as openai_err:
                print(f"❌ OpenAI Chat Error: {openai_err}")


        # 2. Try Gemini fallback
        if not reply and gemini_model:
            try:
                print(f"🧠 Asking Gemini to chat ({role})...")
                conversation_context = system_prompt + "\n\n"
                for msg in history[-10:]:
                    speaker = "Dentist" if msg["sender"] == "user" else "SmileGuard AI"
                    conversation_context += f"{speaker}: {msg['text']}\n"
                conversation_context += f"User: {user_message}\nSmileGuard AI:"

                response = gemini_model.generate_content(conversation_context)
                reply = response.text.strip()
                print("✅ Gemini chat reply generated!")
            except Exception as gemini_err:
                print(f"❌ Gemini Chat Error: {gemini_err}")

        # 3. Local Rule-Based Fallback
        if not reply:
            print("⚠️ Using local dental rule-based chatbot fallback.")
            reply = generate_fallback_chat_reply(user_message, role)

        print(f"💬 Chat ({role}): {user_message[:50]}... → reply returned")
        return jsonify({"reply": reply})

    except Exception as e:
        print(f"❌ Critical Chat endpoint error: {e}")
        return jsonify({"reply": "Sorry, I ran into an issue processing your request. Please try again."}), 200



if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"Starting ProphyDent AI Server on port {port}...")
    app.run(host='0.0.0.0', port=port)
